#!/usr/bin/env bash
set -euo pipefail

VERSION="${EVOPILOT_DASHBOARD_INSTALL_VERSION:-1.0.13}"
DIR="${EVOPILOT_DASHBOARD_INSTALL_DIR:-evopilot-dashboard-run}"
IMAGE="${EVOPILOT_DASHBOARD_IMAGE:-ghcr.io/yeliang-wang/evopilot-dashboard:${VERSION}}"
API_URL="${EVOPILOT_API_BASE_URL:-http://host.docker.internal:19876}"
NETWORK="${EVOPILOT_DOCKER_NETWORK:-}"
PORT="${EVOPILOT_DASHBOARD_PORT:-8080}"
START=0
FORCE=0
SKIP_VERIFY=0

usage() {
  cat <<USAGE
EvoPilot Dashboard container installer

Usage:
  install.sh [--dir evopilot-dashboard-run] [--api-url http://127.0.0.1:19876] [--network evopilot_default] [--port 8080] [--start]

Environment:
  EVOPILOT_DASHBOARD_INSTALL_VERSION   image tag default. Default: ${VERSION}
  EVOPILOT_DASHBOARD_IMAGE             full image reference. Default: ${IMAGE}
  EVOPILOT_API_BASE_URL                EvoPilot API URL from the Dashboard container. Default: ${API_URL}
  EVOPILOT_DOCKER_NETWORK              existing Docker network for API service discovery. Default: empty
  EVOPILOT_DASHBOARD_PORT              host port. Default: ${PORT}
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --dir)
      DIR="${2:?--dir requires a value}"
      shift 2
      ;;
    --api-url)
      API_URL="${2:?--api-url requires a value}"
      shift 2
      ;;
    --image)
      IMAGE="${2:?--image requires a value}"
      shift 2
      ;;
    --network)
      NETWORK="${2:?--network requires a value}"
      shift 2
      ;;
    --port)
      PORT="${2:?--port requires a value}"
      shift 2
      ;;
    --start)
      START=1
      shift
      ;;
    --force)
      FORCE=1
      shift
      ;;
    --skip-verify)
      SKIP_VERIFY=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "install.sh: unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

mkdir -p "$DIR"

write_file() {
  local file="$1"
  if [ -e "$file" ] && [ "$FORCE" -ne 1 ]; then
    echo "install.sh: $file already exists. Re-run with --force to overwrite generated files." >&2
    exit 1
  fi
  cat > "$file"
}

{
cat <<COMPOSE
name: evopilot-dashboard

services:
  evopilot-dashboard:
    image: \${EVOPILOT_DASHBOARD_IMAGE:-${IMAGE}}
    ports:
      - "\${EVOPILOT_DASHBOARD_PORT:-${PORT}}:8080"
    environment:
      EVOPILOT_API_BASE_URL: "\${EVOPILOT_API_BASE_URL:-${API_URL}}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
COMPOSE
if [ -n "$NETWORK" ]; then
cat <<COMPOSE
    networks:
      - evopilot-control-plane
COMPOSE
fi
cat <<COMPOSE
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/health >/dev/null"]
      interval: 20s
      timeout: 5s
      retries: 10
    restart: unless-stopped
COMPOSE
if [ -n "$NETWORK" ]; then
cat <<COMPOSE

networks:
  evopilot-control-plane:
    name: "\${EVOPILOT_DOCKER_NETWORK:-${NETWORK}}"
    external: true
COMPOSE
fi
} | write_file "$DIR/compose.yaml"

write_file "$DIR/README.md" <<README
# EvoPilot Dashboard Run Directory

Generated by the EvoPilot Dashboard installer.

\`\`\`bash
docker compose up -d
./verify.sh
\`\`\`

- Dashboard: http://127.0.0.1:${PORT}
- EvoPilot API: ${API_URL}
- Docker network: ${NETWORK:-default}
- Image: ${IMAGE}
README

write_file "$DIR/verify.sh" <<VERIFY
#!/usr/bin/env bash
set -euo pipefail

curl -fsS "http://127.0.0.1:${PORT}/health" >/dev/null
curl -fsSI "http://127.0.0.1:${PORT}/" >/dev/null

echo "EvoPilot Dashboard is reachable."
VERIFY

chmod 755 "$DIR/verify.sh"

if [ "$START" -eq 1 ]; then
  (cd "$DIR" && docker compose up -d)
  if [ "$SKIP_VERIFY" -ne 1 ]; then
    (cd "$DIR" && ./verify.sh)
  fi
else
  cat <<NEXT
EvoPilot Dashboard run directory generated in ${DIR}

Next:
  cd '${DIR}'
  docker compose up -d
  ./verify.sh
NEXT
fi
